version: '3.1'
services:
  db:
    container_name: postgres-boilerplate
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_boiler_plate
    ports:
      - "5432:5432"

  api:
    container_name: go-boilerplate
    build: .
    environment:
      DB_NAME: go_boiler_plate
      DB_HOST: db
    ports:
    - "8080:8080"
    depends_on:
      - db