version: '3.1'
services:
  db:
    container_name: postgres-boilerplate
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_boiler_plate
    ports:
      - "5432:5432"